# Generated by Django 4.2.5 on 2023-09-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(default='default_image.jpg', null=True, upload_to='images/'),
        ),
    ]
